### ISSUE TITLE
feat: add more license options

### ISSUE THREAD

**Issue by msclock** [serious-scaffold/serious-scaffold-python#186]
Add more options as below:
- Academic Free License v3.0
- Apache License 2.0
- Artistic License 2.0
- BSD 2-Clause "Simplified" License
- BSD 3-Clause Clear License
- BSD 3-Clause "New" or "Revised" License
- Boost Software License 1.0
- Creative Commons Attribution 4.0
- Creative Commons Attribution Share Alike 4.0
- Creative Commons Zero v1.0 Universal
- Do What The F*ck You Want To Public License
- Educational Community License v2.0
- Eclipse Public License 1.0
- Eclipse Public License 2.0
- European Union Public License 1.1
- European Union Public License 1.2
- GNU Affero General Public License v3.0
- GNU General Public License v2.0
- GNU General Public License v3.0
- GNU Lesser General Public License v2.1
- GNU Lesser General Public License v3.0
- ISC License
- LaTeX Project Public License v1.3c
- MIT License
- Mozilla Public License 2.0
- Microsoft Public License
- Microsoft Reciprocal License
- University of Illinois/NCSA Open Source License
- SIL Open Font License 1.1
- Open Software License 3.0
- PostgreSQL License
- The Unlicense
- zlib License

**Comment by huxuan** [comment]
This is a great feature I want to support but did not. The key point is that I personally do not want to maintain the whole list especially for the license template for all possible options. Maybe we can integrate with something like https://choosealicense.com/? Actually, I did not investigate more on it. Let me know if you have any suggestions. :-)

**Comment by msclock** [comment]
> This is a great feature I want to support but did not. The key point is that I personally do not want to maintain the whole list especially for the license template for all possible options. Maybe we can integrate with something like https://choosealicense.com/? Actually, I did not investigate more on it. Let me know if you have any suggestions. :-)

That's a real great option. Also, I know it first time that licenses are well-grouped on it.

**Comment by huxuan** [comment]
> That's a real great option. Also, I know it first time that licenses are well-grouped on it.

GitHub also provide an API to `Get A License`[https://docs.github.com/en/rest/licenses/licenses?get-a-license=&apiVersion=2022-11-28#get-a-license]. I would suggest to use this kind of services instead.

**Comment by msclock** [comment]
> > That's a real great option. Also, I know it first time that licenses are well-grouped on it.
> 
> GitHub also provide an API to [Get A License](https://docs.github.com/en/rest/licenses/licenses?get-a-license=&apiVersion=2022-11-28#get-a-license). I would suggest to use this kind of services instead.

After reading it, it seems that a token is needed to use the API. But the token is not possible to expose to consumers by hard-coding.

**Comment by huxuan** [comment]
> After reading it, it seems that a token is needed to use the API. But the token is not possible to expose to consumers by hard-coding.

Yep, it is true. I mean the API is just another possible option. If possible, I would prefer not to maintain all the license contents in the repo.

I will also do more investigation myself. Will come up again after some progress.

**Comment by msclock** [comment]
We can use jinja to render license template under the folder https://github.com/github/choosealicense.com/tree/gh-pages/_licenses @huxuan

**Comment by huxuan** [comment]
After some brief investigation, seems there is no well-maintained **jinja** template for open source licenses. Even for the choosealicense repo, it is a txt file and fields are not formatted in jinja variables. Maybe we have to maintain it ourselves. I will add more comments in the corresponding PR.
